export default {
  name: 'character',
  title: 'Character',
  type: 'document',
  fields: [
    { name: 'name', title: 'Name', type: 'string', validation: (Rule) => Rule.required() },
    { name: 'slug', title: 'Slug', type: 'slug', options: { source: 'name', maxLength: 96 }, validation: (Rule) => Rule.required() },
    { name: 'role', title: 'Role', type: 'string', description: 'e.g. "The Leader", "The Ghost"' },
    { name: 'badge', title: 'Badge Label', type: 'string', description: 'Short label shown on card' },
    { name: 'tagline', title: 'Tagline', type: 'string' },
    { name: 'bio', title: 'Biography', type: 'text', rows: 4, validation: (Rule) => Rule.required() },
    { name: 'extendedBio', title: 'Extended Bio', type: 'array', of: [{ type: 'block' }] },
    { name: 'traits', title: 'Key Traits', type: 'array', of: [{ type: 'string' }] },
    { name: 'quote', title: 'Signature Quote', type: 'string' },
    { name: 'accent', title: 'Accent Colour (hex)', type: 'string', description: 'e.g. #ff8c00' },
    { name: 'accentDim', title: 'Accent Dim (rgba)', type: 'string' },
    { name: 'accentGlow', title: 'Accent Glow (rgba)', type: 'string' },
    { name: 'initials', title: 'Initials', type: 'string', description: 'e.g. WM, LL' },
    { name: 'portrait', title: 'Character Portrait', type: 'image', options: { hotspot: true } },
    { name: 'galleryImages', title: 'Gallery Images', type: 'array', of: [{ type: 'image', options: { hotspot: true } }] },
    { name: 'sortOrder', title: 'Display Order', type: 'number' },
    { name: 'seoTitle', title: 'SEO Title', type: 'string' },
    { name: 'seoDescription', title: 'SEO Description', type: 'text', rows: 2 },
  ],
  orderings: [{ title: 'Display Order', name: 'sortOrderAsc', by: [{ field: 'sortOrder', direction: 'asc' }] }],
  preview: { select: { title: 'name', subtitle: 'role', media: 'portrait' } },
};
